version: '3.1'

services:
  flyway:
    container_name: flyway
    image: flyway/flyway
    environment:
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: admin
      FLYWAY_URL: jdbc:postgresql://db:5432/
      FLYWAY_SCHEMAS: flyway
      FLYWAY_MIXED: true
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      db:
        condition: service_healthy


  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - "dbData:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      retries: 10
      interval: 3s

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:latest
    restart: always
    environment:
      KEYCLOAK_HTTP_PORT: 8090
      KEYCLOAK_USER: user
      KEYCLOAK_DATABASE_NAME: bn_keycloak
      KEYCLOAK_DATABASE_USER: bn_keycloak
      KEYCLOAK_DATABASE_PASSWORD: admin
      KEYCLOAK_ADMIN_PASSWORD : admin
      KEYCLOAK_DATABASE_HOST: db
    ports:
      - "8090:8090"
    depends_on:
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl http://keycloak:8090/auth/realms/job-portal" ]
      interval: 4s
      retries: 10
    volumes:
      - ./keycloak-theme:/opt/bitnami/keycloak/themes

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
  back-end:
    container_name: back-end
    ports:
      - "8081:8081"
      - "5005:5005"
    build:
      dockerfile: Dockerfile
      context: ./back-end
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/
      SPRING_DATASOURCE_HOST: db
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8090
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://keycloak:8090/realms/job-portal/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://localhost:8090/realms/job-portal
      SPRING_MAIL_HOST: mailhog
    depends_on:
      keycloak:
        condition: service_healthy
      mailhog:
        condition: service_started
    volumes:
      - ./assets:/usr/share/assets

  front-end:
    container_name: front-end
    ports:
      - "80:80"
    build:
      dockerfile: Dockerfile
      context: ./front-end
volumes:
  dbData:

