CREATE ROLE bn_keycloak WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'admin';

CREATE DATABASE bn_keycloak
	WITH
	OWNER = bn_keycloak
	ENCODING = 'UTF8'
	CONNECTION LIMIT = -1
	IS_TEMPLATE = False;
